class SceneManager{
    static activeScene;
    static Load(sceneName){
        entities = [];
        for(let i = 1; i <= Time.allCurrentTimeouts.length; i++){
            clearTimeout(Time.allCurrentTimeouts[i - 1]);
        }
        SceneManager.LoadOntop(sceneName);
    }
    static LoadOntop(sceneName){
        let t0 = performance.now();
        this.activeScene = sceneName;
        sceneName();
        let t1 = performance.now();
        console.log("LoadTime | " + ((t1 - t0) / 1000).toString() + " Seconds");
    }
    static Scene1(){
        spawnEntity(new Entity("Player", "Player", [new Renderer(0, "https://Seiji-Welsh.github.io/Game/Images/Crate.png", 16, 16, false)
        , new RectangleCollider(16, 16, 0, 0), new PlayerController(), new Physics(.5, 1.2, 1, 1, 1)]), 0, 0, 1, 1, 0)
        spawnEntity(new Entity("MouseObject", "ForeGround", [new MouseObject()]), 0, 0, 1, 1, 0)
        spawnEntity(new Entity("FPSUI", "UI", [new TextRendererUI("FPS: " + Math.round(randomRange(45, 52)), "left", "40px Calibri", "rgb(40, 40, 40)"), new FPSUI()]), 10, canvas.height - 50, 1, 1, 0)
        spawnEntity(new Entity("LevelManager", "NONE", [new LevelController()]), 0, 0, 1, 1, 0)
        spawnEntity(new Entity("HTMLController", "NONE", [new HTMLController()], 0, 0, 1, 1, 0))
        mainCamera = spawnEntity(new Entity("MainCamera", "camera", [new Camera(), new CameraEditorController()]), 0, 0, 1, 1, 0);
        SceneManager.Scene1Tiles();
    }
    static Scene2(){
        spawnEntity(new Entity("Player", "Player", [new Renderer(0, "https://Seiji-Welsh.github.io/Game/Images/Crate.png", 16, 16, false)
        , new RectangleCollider(16, 16, 0, 0), new PlayerController(), new Physics(.5, 1.2, 1, 1, 1)]), 0, 0, 1, 1, 0)
        spawnEntity(new Entity("MouseObject", "ForeGround", [new MouseObject()]), 0, 0, 1, 1, 0)
        spawnEntity(new Entity("FPSUI", "UI", [new TextRendererUI("FPS: " + Math.round(randomRange(45, 52)), "left", "40px Calibri", "rgb(40, 40, 40)"), new FPSUI()]), 10, canvas.height - 50, 1, 1, 0)
        spawnEntity(new Entity("LevelManager", "NONE", [new LevelController()]), 0, 0, 1, 1, 0)
        spawnEntity(new Entity("HTMLController", "NONE", [new HTMLController()], 0, 0, 1, 1, 0))
        mainCamera = spawnEntity(new Entity("MainCamera", "camera", [new Camera(), new CameraEditorController()]), 0, 0, 1, 1, 0);
        SceneManager.Scene2Tiles(); 
    }
    static Scene1Tiles(){
        
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUpRight.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),128,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideLeftUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-128,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstCornerSW.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstCornerSE.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideRightDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),128,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideDownLeft.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-128,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideDownLeft.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstCornerSW.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstCornerSE.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideRightDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideRightDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-128,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-128,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-128,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-128,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideDownLeft.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-128,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-192,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-192,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-128,-192,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-160,-192,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-160,-224,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-192,-224,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-192,-256,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-192,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-160,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-128,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-128,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-160,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-192,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),128,-256,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-256,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-256,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),128,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),128,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),160,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),288,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),320,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),416,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),416,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),416,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),384,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),384,-256,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),352,-256,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),320,-256,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),320,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),320,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),352,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),352,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),352,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),384,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),384,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),416,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),512,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),512,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),512,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),512,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),512,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),544,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),576,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),608,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),608,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),640,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),640,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),640,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),736,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),768,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),800,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),800,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),832,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),832,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),832,-256,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),800,-256,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),768,-256,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),768,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),736,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),736,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),704,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),704,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),704,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),736,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),736,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),768,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),800,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1088,-160,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1088,-192,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1088,-224,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1088,-256,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1088,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1056,-288,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1056,-320,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1056,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1088,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),960,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),992,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1024,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1056,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1088,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1120,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1120,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1152,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1056,-128,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1056,-160,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1024,-160,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1024,-192,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),992,-192,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),992,-224,1,1,0)

    }
    static Scene2Tiles(){

spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideDownLeft.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-128,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideLeft.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-128,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideDownLeft.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-160,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideLeft.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-224,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideDownLeft.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-256,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideRightDownLeft.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-288,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstCornerSWSE.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-256,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideRightDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-256,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideRight.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-224,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstCornerSE.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-192,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideRightDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-192,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideRight.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-160,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideRightDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-128,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideRight.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideRightDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),128,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUpRightDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),160,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUpCornerSE.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),128,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideLeftUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-160,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideDownLeft.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-160,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstCornerSW.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-128,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstCornerSW.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-160,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideLeft.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-192,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-224,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-192,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstCornerSW.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-128,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-128,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideUp.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-32,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstCornerSE.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-64,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-128,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstCornerSE.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-128,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstSideDown.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-128,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-96,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-128,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-160,1,1,0)
spawnEntity(new Entity("round","ground",[new Renderer(-1,"https://seiji-welsh.github.io/Game/Images/Tiles/RoundTilesTest/RndTlsTstNone.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-160,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-160,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-192,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-224,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-256,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-288,-352,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-320,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-352,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-352,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-320,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-320,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-320,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-288,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-256,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-256,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-224,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-192,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-192,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-192,-576,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-224,-576,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-224,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-256,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-576,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-576,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),256,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),288,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),320,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),320,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),352,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),352,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),320,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),320,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),288,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),256,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),256,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),224,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),192,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),192,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),192,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),224,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),224,-576,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),256,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),256,-640,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),288,-640,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),320,-672,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),352,-672,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),384,-672,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),512,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),544,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),544,-576,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),576,-576,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),576,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),576,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),576,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),576,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),576,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),608,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),640,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),672,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),704,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),736,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),768,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),800,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),800,-576,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),800,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),928,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),960,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),992,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1024,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1056,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1056,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1056,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1024,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),992,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),960,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),928,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),896,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),896,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),896,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),896,-576,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),928,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),928,-640,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),960,-640,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1152,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1152,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1184,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1216,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1248,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1280,-384,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1280,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1312,-416,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1312,-448,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1312,-480,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1312,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1280,-512,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1280,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1248,-544,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1248,-576,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1216,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1184,-608,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1152,-640,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1184,-640,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1216,-640,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1248,-640,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1280,-640,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(0,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),1312,-640,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-32,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),64,-32,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),96,-32,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),32,-32,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-128,-32,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-96,-32,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-32,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-32,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-64,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-64,-96,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-96,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-128,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-224,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-192,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-160,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-160,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-128,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-96,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),0,-64,1,1,0)
spawnEntity(new Entity("wood","ground",[new Renderer(1,"https://seiji-welsh.github.io/Game/Images/Tiles/Wood/Wood.png",32,32,false),new RectangleCollider(32,32,0,0)],"tile"),-32,-64,1,1,0)
    }
}